apiVersion: v1
kind: Service
metadata:
  name: luizalabs-api
  namespace: {{NAMESPACE}}
  labels:
    app: luizalabs
spec:
  selector:
    app: luizalabs
  ports:
  - name: http
    port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: luizalabs-api
  namespace: default
spec: 
  hosts: 
  - luizalabs.example.com
  gateways:
  - luizalabs-gateway
  http:
  - route:
    - destination:
        port: 
          number: 80
        host: luizalabs-api.{{NAMESPACE}}.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: luizalabs-api
  namespace: {{NAMESPACE}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: luizalabs
    spec:
      containers:
      - name: luizalabs-api
        image: {{IMAGE}}
        imagePullPolicy: Always
        env: 
        - name: CONFIG_PATH
          value: /root/config.json
        resources: 
          requests: 
            cpu: "200m"
            memory: "300Mi"
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: config
          mountPath: "/root"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        secret: 
          secretName: luizalabs-api-config
      imagePullSecrets:
        - name:  gitlab
