apiVersion: v1
kind: Service
metadata:
  name: luizalabs-db
  namespace: {{NAMESPACE}}
  labels:
    app: luizalabs
spec:
  type: ClusterIP
  selector:
    app: luizalabs
  ports:
  - port: 5432
    name: database
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: {{NAMESPACE}}
  labels:
    app: luizalabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luizalabs
  template:
    metadata:
      labels:
        app: luizalabs
      annotations:
        backup-command: pg_dump -U admin luizalabs
        backup-filename: luizalabs-db-ENVIRONMENT/postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:10.5-alpine
          args: ['-c', 'config_file=/etc/postgresql/postgresql.conf', '-c', 'hba_file=/etc/postgresql/pg_hba.conf']
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: luizalabs-db-config
                  key: postgres-db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: luizalabs-db-config
                  key: postgres-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: luizalabs-db-config
                  key: postgres-password

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3

          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data/pgdata
            - name: postgres-config
              mountPath: /etc/postgresql

      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
        - name: postgresdb
          persistentVolumeClaim:
            claimName: luizalabs-pvc
