kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: luizalabs-pvc
  namespace: NAMESPACE
  labels:
    app: luizalabs
spec:
  storageClassName: gcepd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
